[package]
name = "xnote-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
ignore = "0.4.23"
ropey = "1.6"
pulldown-cmark = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
notify = "6.1"
ureq = { version = "2.12", features = ["json"] }
